### PR TITLE
Upgraded math.js to newest production version to remove counter doubl…

### PR DESCRIPTION
**Pull request by AnotherStranger**
Upgraded math.js to newest production version to remove counter double precision errors

I upgraded math.js to the newest release and did minor changes so the calculator app can use and load it. Before the upgrade 0.1+0.2 was 0.30000004 now it calculates the correct value 0.3.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This looks good to me (and the included math.js is exactly the same as the upstream from [cdn.js](https://cdnjs.cloudflare.com/ajax/libs/mathjs/5.2.2/math.min.js)), but I think I'd like @bhdouglass to do the full review.

**Comment by bhdouglass** [comment]
What do you think about using npm to include this or something? Rather than having to update it manually every time, we can just use npm to track updates.

**Comment by AnotherStranger** [comment]
i think using npm would be the best way.
However i'm not particulary experienced in JavaScript or qml.

**Comment by bhdouglass** [comment]
Ok, I'm going to merge this and then check out using npm. Thanks!

**Pull request merged**
